### ISSUE TITLE
Multiple attachments are overwritten with last attachment using Attach()

### ISSUE THREAD

**Issue by andysnowden** [go-mail/gomail#53]
Per original issue https://github.com/go-gomail/gomail/issues/126 this is still happening.  The issue however does not occur when using the AttachReader() variant

**Comment by steviesama** [comment]
@andysnowden  I haven't sent multiple with this repo yet...but I have code in production using the old repo and `Attach()` was resulting in all the appropriate attachments. Is there a way to reproduce this?

I have updated the code to use this active repo though...so if there's gonna be a problem...I'll see it soon.

**Comment by BarakatX2** [comment]
@andysnowden I don't think the problem in that issue is a bug in the library. It is likely the use of the loop variable in a closure. The loop variable `f` gets captured in the closures. When the closures are called after the loop completes, they all use the same variable which contains the last loop value. `SetCopyFunc` takes the given closure and stores it in a `file` object, so by the time the closure is called later it is using the captured loop variable that contains the last loop value. Here is an example showing how the loop variable returns the last loop value while the copied version of the loop variable is the expected value (you can also copy the loop variable by wrapping the loop code with a closure to avoid having a different variable name): https://play.golang.org/p/b6u5Yuce0_J
