### ISSUE TITLE
Add Support For Email Priority

### ISSUE THREAD

**Issue by teschste** [go-mail/gomail#55]
Is there a way to specify an email's priority (low, normal, or high)?  If not, it would be helpful to include that feature, as it is a common method for email clients to prioritize incoming mail.

Thanks!

**Comment by ivy** [comment]
@teschste I'm not sure what other clients support sender-specified priorities outside of Outlook. Have a look [here](http://www.chilkatsoft.com/p/p_471.asp) for more on that. It should be enough to set the appropriate header(s):

```go
msg.SetHeader("X-Priority", "1") // High
msg.SetHeader("X-Priority", "3") // Normal
msg.SetHeader("X-Priority", "5") // Low
```

Otherwise, I don't think there's a proper standard for this. Gmail seems to make its own judgment.

**Comment by teschste** [comment]
Good to know.  Thanks!
